"""Capsule - daily summaries from Postgres.

The past section of the system prompt comes from Capsule summaries:
stored in cortex.summaries, generated by the Capsule service.
"""

import logging
import os

import pendulum

logger = logging.getLogger(__name__)

DATABASE_URL = os.environ.get("DATABASE_URL", "")


def _format_summary(row: tuple) -> str:
    """Format a capsule summary row into a markdown section."""
    period_start, period_end, summary = row

    start = pendulum.instance(period_start).in_timezone("America/Los_Angeles")
    end = pendulum.instance(period_end).in_timezone("America/Los_Angeles")

    is_night = start.hour >= 22 or start.hour < 6

    if is_night:
        header = (
            f"# This part is a summary of the events of "
            f"{start.format('dddd')} night {start.format('MMM')} {start.day}-{end.day} {end.year}"
        )
    else:
        header = f"# This part is a summary of the events of {start.format('dddd MMM D YYYY')}"

    return f"{header}\n\n{summary}"


async def fetch() -> tuple[str | None, str | None]:
    """Get the two most recent Capsule summaries from Postgres.

    Returns (older_summary, newer_summary) as formatted strings,
    or None for each if not available.

    Note: Uses sync psycopg inside async - the query is fast and
    this keeps the code simple. Consider psycopg async pool if needed.
    """
    if not DATABASE_URL:
        logger.debug("No DATABASE_URL, skipping Capsule summaries")
        return None, None

    try:
        import psycopg

        with psycopg.connect(DATABASE_URL) as conn:
            with conn.cursor() as cur:
                cur.execute("""
                    SELECT period_start, period_end, summary
                    FROM cortex.summaries
                    ORDER BY period_start DESC
                    LIMIT 2
                """)
                rows = cur.fetchall()

        if not rows:
            return None, None

        summaries = [_format_summary(row) for row in rows]

        if len(summaries) >= 2:
            return summaries[1], summaries[0]  # (older, newer)
        elif len(summaries) == 1:
            return None, summaries[0]
        else:
            return None, None

    except Exception as e:
        logger.warning(f"Error fetching Capsule summaries: {e}")
        return None, None
